name: Merge to main

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and test application
      run: mvn test
    - name: Merge to main
      if: success()
      uses: actions/create-pull-request@v2
      with:
        title: Merge dev to main
        head: dev
        base: main
        body: |
          This pull request merges the dev branch into the main branch.
          The dev branch has passed all tests and is ready to be merged.
